[project]
name = "process-template"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "automation-server-client",
    "ky-client",
    "momentum-client",
    "odk-tools",
    "ruff>=0.16.1",
]

[tool.uv.sources]
automation-server-client = { git = "https://github.com/odense-rpa/automation-server-client.git", tag = "v0.3.0" }
momentum-client = { git = "https://github.com/odense-rpa/momentum-client.git" }
ky-client = { git = "https://github.com/odense-rpa/ky-client.git" }
odk-tools = { git = "https://github.com/odense-rpa/odk-tools.git" }
